name: PHP Composer

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict

    #- name: Install dependencies
    #  run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    - name: Build directory
      run: mkdir .secret

    - name: Build config
      run: |
        echo "{\"external\":{\"switchbot\":{\"credential\":{\"client_token\":\"${{secrets.switchbot_client_token}}\",\"client_secret\":\"${{secrets.switchbot_client_secret}}\"}}}}" | tee .secret/config.json

    - name: Run php
      run: for i in *.php; do sleep 1; echo "> php ${i}"; php ${i} | jq | tee github-action-run_$(date +%s).json; done

    - name: Send discord
      run: |
        for i in github-action-run*; do curl -X POST -H 'Content-Type:multipart/form-data' -F 'file=@'${i} -F $'content=Launched github action: n138-kz/switchbot.\nRepository: https://github.com/n138-kz/switchbot/' ${{secrets.discord_webhook_url}}; done
