name: PHP Runner

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */6 * * *"

env:
  discord_avatar_url: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
  discord_username: Github-Actions
  github_context: content=`["GITHUB_REPOSITORY":"${{ github.repository }}","GITHUB_REF_NAME":"${{ github.ref_name }}"]`

permissions:
  contents: read

jobs:
  send_github_context:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Send GITHUB Context
      run: curl -X POST -d 'avatar_url=${{ env.discord_avatar_url }}' -d 'username=${{ env.discord_username }}' -d '${{ env.github_context }}' ${{ secrets.discord_webhook_url }}

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    #- name: Send GITHUB Context
    #  run: curl -X POST -d 'avatar_url=${{ env.discord_avatar_url }}' -d 'username=${{ env.discord_username }}' -d $'content=`["GITHUB_REPOSITORY":"'${{ github.repository }}'","GITHUB_REF_NAME":"'${{ github.ref_name }}'"]`' ${{secrets.discord_webhook_url}}

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict

    #- name: Install dependencies
    #  run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    - name: Build directory
      run: mkdir .secret

    - name: Build config
      run: |
        echo "{\"external\":{\"switchbot\":{\"credential\":{\"client_token\":\"${{secrets.switchbot_client_token}}\",\"client_secret\":\"${{secrets.switchbot_client_secret}}\"}}}}" | tee .secret/config.json
        cat .secret/config.json | jq

    - name: Run php
      run: for i in *.php; do sleep 1; for j in {0..9}; do echo '>'; done; echo "> php ${i}"; echo '# '$(date); php ${i} | jq | tee github-action-run_${i%.*}.json; done

    - name: Send discord
      run: |
        for i in github-action-run*; do curl -X POST -H 'Content-Type:multipart/form-data' -F 'avatar_url=${{ env.discord_avatar_url }}' -F 'username=${{ env.discord_username }}' -F 'file=@'${i} -F $'content=Launched github action: [${{github.repository}}](https://github.com/${{github.repository}}).\n' ${{secrets.discord_webhook_url}} | jq; done

    #- name: Send discord
    #  run: curl -X POST -d 'avatar_url=${{ env.discord_avatar_url }}' -d 'username=Github-Actions' -d $'content=Execute manual scenes\n```http\nPOST /v1.1/scenes/{sceneId}/execute\n```' ${{secrets.discord_webhook_url}}
