name: PHP Runner

on:
  workflow_dispatch:
    inputs:
      sceneId:
        required: true
        type: string
      runCount:
        type: number
        default: 1
  push:
  schedule:
    - cron: "0 */6 * * *"

env:
  discord_avatar_url: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
  discord_username: Github-Actions
  github_context: '{"GITHUB_REPOSITORY":"${{ github.repository }}","GITHUB_REF_NAME":"${{ github.ref_name }}","GITHUB_TOKEN":"${{ github.token }}","GITHUB_ACTION":"${{ github.action }}","GITHUB_ACTION_PATH":"${{ github.action_path }}","GITHUB_SHA":"${{ github.sha }}","GITHUB_WORKFLOW":"${{ github.workflow }}","GITHUB_JOB":"${{ github.job }}","GITHUB_ENV":"${{ github.env }}","GITHUB_EVENT":"${{ github.event }}","GITHUB_EVENT_NAME":"${{ github.event_name }}"}'
  switchbot_context: '{"external":{"switchbot":{"credential":{"client_token":"${{ secrets.switchbot_client_token }}","client_secret":"${{ secrets.switchbot_client_secret }}" },"apimanuals":"${{ github.server_url }}/OpenWonderLabs/SwitchBotAPI"}}}'

permissions:
  contents: read

jobs:
  send_github_context:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare file for GITHUB Context
      run: |
        echo '${{ env.github_context }}' | jq | tee github-action-run_github-context.json

    - name: Get the GITHUB RestAPI /repos
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }} | jq | tee github-action-run_github-repos.json
  
    - name: Send discord
      run: |
        for i in github-action-run*; do curl -X POST -H 'Content-Type:multipart/form-data' -F 'avatar_url=${{ env.discord_avatar_url }}' -F 'username=${{ env.discord_username }}' -F 'file=@'${i} -F $'content=Launched github action: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions).\n' ${{ secrets.discord_webhook_url }} | jq; done

  send_switchbot_context:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare file for SWITCHBOT Context
      run: |
        echo '${{ env.switchbot_context }}' | jq | tee github-action-run_switchbot-context.json

    - name: Send discord
      run: |
        for i in github-action-run*; do curl -X POST -H 'Content-Type:multipart/form-data' -F 'avatar_url=${{ env.discord_avatar_url }}' -F 'username=${{ env.discord_username }}' -F 'file=@'${i} -F $'content=Launched github action: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions).\n' ${{ secrets.discord_webhook_url }} | jq; done
      
  testrun:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build directory
      run: mkdir .secret

    - name: Build config
      run: |
        echo '${{ env.switchbot_context }}' | tee .secret/config.json
        cat .secret/config.json | jq

    - name: Run php
      run: for i in example_*.php; do sleep 1; for j in {0..9}; do echo '>'; done; echo "> php ${i}"; echo '# '$(date); php ${i} | jq | tee github-action-run_${i%.*}.json; done

    - name: Send discord
      run: |
        for i in github-action-run*; do curl -X POST -H 'Content-Type:multipart/form-data' -F 'avatar_url=${{ env.discord_avatar_url }}' -F 'username=${{ env.discord_username }}' -F 'file=@'${i} -F $'content=Launched github action: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions).\n' ${{ secrets.discord_webhook_url }} | jq; done

    #- name: Send discord
    #  run: curl -X POST -d 'avatar_url=${{ env.discord_avatar_url }}' -d 'username=Github-Actions' -d $'content=Execute manual scenes\n```http\nPOST /v1.1/scenes/{sceneId}/execute\n```' ${{ secrets.discord_webhook_url }}

  testrun_activate_scene:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build directory
      run: mkdir .secret

    - name: Build config
      run: |
        echo '${{ env.switchbot_context }}' | tee .secret/config.json
        cat .secret/config.json | jq

    - name: Build config
      run: |
        echo '{"runCount": ${{ inputs.runCount || 0 }},"sceneId":["${{ inputs.sceneId }}"]}' | tee .secret/activate_scenes.json
        cat .secret/activate_scenes.json | jq

    - name: Run php
      run: for i in rw_example_*.php; do sleep 1; for j in {0..9}; do echo '>'; done; echo "> php ${i}"; echo '# '$(date); php ${i} | jq | tee github-action-run_${i%.*}.json; done

    - name: Send discord
      run: |
        for i in github-action-run*; do curl -X POST -H 'Content-Type:multipart/form-data' -F 'avatar_url=${{ env.discord_avatar_url }}' -F 'username=${{ env.discord_username }}' -F 'file=@'${i} -F $'content=Launched github action: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions).\n' ${{ secrets.discord_webhook_url }} | jq; done
